services:
  booking-postgres:
    image: postgres:latest
    volumes:
      - booking-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: itzyaboirey
      POSTGRES_PASSWORD: reymooY27
      POSTGRES_DB: booking-service
    networks:
      - app-network

  payment-postgres:
    image: postgres:latest
    volumes:
      - payment-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: itzyaboirey
      POSTGRES_PASSWORD: reymooY27
      POSTGRES_DB: payment-service
    networks:
      - app-network

  auth-postgres:
    image: postgres:latest
    volumes:
      - auth-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: itzyaboirey
      POSTGRES_PASSWORD: reymooY27
      POSTGRES_DB: auth-service
    networks:
      - app-network

  arena-postgres:
    image: postgres:latest
    volumes:
      - arena-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: itzyaboirey
      POSTGRES_PASSWORD: reymooY27
      POSTGRES_DB: arena-service
    networks:
      - app-network

  arena-service:
    depends_on:
      - arena-postgres
    image: arena-service:latest
    build:
      context: ./arena-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - DB_URL=postgresql://itzyaboirey:reymooY27@arena-postgres:5432/arena-service?sslmode=disable
      - PORT=8000
      - SECRET=secret

  auth-service:
    depends_on:
      - auth-postgres
    image: auth-service:latest
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - app-network
    environment:
      - DB_URL=postgresql://itzyaboirey:reymooY27@auth-postgres:5432/auth-service?sslmode=disable
      - PORT=8001
      - SECRET=secret

  booking-service:
    depends_on:
      - booking-postgres
    image: booking-service:latest
    build:
      context: ./booking-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    networks:
      - app-network
    environment:
      - DB_URL=postgresql://itzyaboirey:reymooY27@booking-postgres:5432/booking-service?sslmode=disable
      - PORT=8002
      - SECRET=secret
      - ARENA_SERVICE_URL=http://arena-service:8000
      - USER_SERVICE_URL=http://auth-service:8001

  payment-service:
    depends_on:
      - payment-postgres
    image: payment-service:latest
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "50001:50001"
    networks:
      - app-network
    environment:
      - DB_URL=postgresql://itzyaboirey:reymooY27@payment-postgres:5432/payment-service?sslmode=disable
      - PORT=50001
      - SECRET=secret

  api-gateway:
    image: api-gateway:latest
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - PORT=5000
      - SECRET=secret
      - PAYMENT_SERVICE_URL=payment-service:50001

networks:
  app-network:
    driver: bridge

volumes:
  booking-postgres:
  auth-postgres:
  arena-postgres:
  payment-postgres:
