services:
  auth-service:
    image: auth-service:latest
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    env_file: ./auth-service/.env

  arena-service:
    image: arena-service:latest
    build:
      context: ./arena-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-network
    env_file: ./arena-service/.env

  # db:
  #   image: postgres:latest
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   networks:
  #     - app-network

networks:
  app-network:
# volumes:
#   db-data:
