apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
data:
  DB_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzLmx6Y2Z6b2pzaWtkbGdmYmFvcnR3OklQSHFpZVNST1RkVE5acnZAYXdzLTAtYXAtc291dGhlYXN0LTEucG9vbGVyLnN1cGFiYXNlLmNvbTo2NTQzL3Bvc3RncmVzP3BnYm91bmNlcj10cnVl
  SECRET: c2VjcmV0
