// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.0--rc2
// source: proto/arena.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArenaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *ArenaRequest) Reset() {
	*x = ArenaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_arena_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArenaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArenaRequest) ProtoMessage() {}

func (x *ArenaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arena_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArenaRequest.ProtoReflect.Descriptor instead.
func (*ArenaRequest) Descriptor() ([]byte, []int) {
	return file_proto_arena_proto_rawDescGZIP(), []int{0}
}

func (x *ArenaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArenaRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ArenaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ArenaResponse) Reset() {
	*x = ArenaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_arena_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArenaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArenaResponse) ProtoMessage() {}

func (x *ArenaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arena_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArenaResponse.ProtoReflect.Descriptor instead.
func (*ArenaResponse) Descriptor() ([]byte, []int) {
	return file_proto_arena_proto_rawDescGZIP(), []int{1}
}

func (x *ArenaResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ArenaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetArenaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArenaId int64 `protobuf:"varint,1,opt,name=arena_id,json=arenaId,proto3" json:"arena_id,omitempty"`
}

func (x *GetArenaRequest) Reset() {
	*x = GetArenaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_arena_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetArenaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArenaRequest) ProtoMessage() {}

func (x *GetArenaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arena_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArenaRequest.ProtoReflect.Descriptor instead.
func (*GetArenaRequest) Descriptor() ([]byte, []int) {
	return file_proto_arena_proto_rawDescGZIP(), []int{2}
}

func (x *GetArenaRequest) GetArenaId() int64 {
	if x != nil {
		return x.ArenaId
	}
	return 0
}

type UpdateArenaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArenaId     int64  `protobuf:"varint,1,opt,name=arena_id,json=arenaId,proto3" json:"arena_id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *UpdateArenaRequest) Reset() {
	*x = UpdateArenaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_arena_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateArenaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArenaRequest) ProtoMessage() {}

func (x *UpdateArenaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arena_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArenaRequest.ProtoReflect.Descriptor instead.
func (*UpdateArenaRequest) Descriptor() ([]byte, []int) {
	return file_proto_arena_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateArenaRequest) GetArenaId() int64 {
	if x != nil {
		return x.ArenaId
	}
	return 0
}

func (x *UpdateArenaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateArenaRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ArenaData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArenaId     int64                  `protobuf:"varint,1,opt,name=arena_id,json=arenaId,proto3" json:"arena_id,omitempty"`
	Name        string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *ArenaData) Reset() {
	*x = ArenaData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_arena_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArenaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArenaData) ProtoMessage() {}

func (x *ArenaData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arena_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArenaData.ProtoReflect.Descriptor instead.
func (*ArenaData) Descriptor() ([]byte, []int) {
	return file_proto_arena_proto_rawDescGZIP(), []int{4}
}

func (x *ArenaData) GetArenaId() int64 {
	if x != nil {
		return x.ArenaId
	}
	return 0
}

func (x *ArenaData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArenaData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ArenaData) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListArenaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arenas []*ArenaData `protobuf:"bytes,1,rep,name=arenas,proto3" json:"arenas,omitempty"`
}

func (x *ListArenaResponse) Reset() {
	*x = ListArenaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_arena_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListArenaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArenaResponse) ProtoMessage() {}

func (x *ListArenaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_arena_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArenaResponse.ProtoReflect.Descriptor instead.
func (*ListArenaResponse) Descriptor() ([]byte, []int) {
	return file_proto_arena_proto_rawDescGZIP(), []int{5}
}

func (x *ListArenaResponse) GetArenas() []*ArenaData {
	if x != nil {
		return x.Arenas
	}
	return nil
}

var File_proto_arena_proto protoreflect.FileDescriptor

var file_proto_arena_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x72, 0x65, 0x6e, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x0c, 0x41, 0x72, 0x65, 0x6e,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x43,
	0x0a, 0x0d, 0x41, 0x72, 0x65, 0x6e, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0x2c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x6e, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x72, 0x65, 0x6e, 0x61, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x72, 0x65, 0x6e, 0x61, 0x49,
	0x64, 0x22, 0x65, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x6e, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x72, 0x65, 0x6e, 0x61,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x72, 0x65, 0x6e, 0x61,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x97, 0x01, 0x0a, 0x09, 0x41, 0x72, 0x65,
	0x6e, 0x61, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x72, 0x65, 0x6e, 0x61, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x72, 0x65, 0x6e, 0x61, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x22, 0x3d, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x6e, 0x61, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x61, 0x72, 0x65, 0x6e, 0x61,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x41, 0x72, 0x65, 0x6e, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x06, 0x61, 0x72, 0x65, 0x6e, 0x61,
	0x73, 0x32, 0xbe, 0x02, 0x0a, 0x0c, 0x41, 0x72, 0x65, 0x6e, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x6e,
	0x61, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x72, 0x65, 0x6e, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41,
	0x72, 0x65, 0x6e, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0b,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x72, 0x65, 0x6e, 0x61, 0x12, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x6e, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x72, 0x65, 0x6e,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x6e, 0x61, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x72, 0x65, 0x6e, 0x61, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x72, 0x65, 0x6e,
	0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0c, 0x47, 0x65, 0x74,
	0x41, 0x72, 0x65, 0x6e, 0x61, 0x42, 0x79, 0x49, 0x64, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x6e, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x72, 0x65, 0x6e, 0x61, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x3d, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x72, 0x65, 0x6e, 0x61, 0x73,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x65, 0x6e, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x72, 0x65, 0x79, 0x6d, 0x6f, 0x6f, 0x79, 0x32, 0x37, 0x2f, 0x61, 0x72, 0x65, 0x6e, 0x61,
	0x2d, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_arena_proto_rawDescOnce sync.Once
	file_proto_arena_proto_rawDescData = file_proto_arena_proto_rawDesc
)

func file_proto_arena_proto_rawDescGZIP() []byte {
	file_proto_arena_proto_rawDescOnce.Do(func() {
		file_proto_arena_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_arena_proto_rawDescData)
	})
	return file_proto_arena_proto_rawDescData
}

var file_proto_arena_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_arena_proto_goTypes = []any{
	(*ArenaRequest)(nil),          // 0: proto.ArenaRequest
	(*ArenaResponse)(nil),         // 1: proto.ArenaResponse
	(*GetArenaRequest)(nil),       // 2: proto.GetArenaRequest
	(*UpdateArenaRequest)(nil),    // 3: proto.UpdateArenaRequest
	(*ArenaData)(nil),             // 4: proto.ArenaData
	(*ListArenaResponse)(nil),     // 5: proto.ListArenaResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 7: google.protobuf.Empty
}
var file_proto_arena_proto_depIdxs = []int32{
	6, // 0: proto.ArenaData.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: proto.ListArenaResponse.arenas:type_name -> proto.ArenaData
	0, // 2: proto.ArenaService.CreateArena:input_type -> proto.ArenaRequest
	2, // 3: proto.ArenaService.DeleteArena:input_type -> proto.GetArenaRequest
	3, // 4: proto.ArenaService.UpdateArena:input_type -> proto.UpdateArenaRequest
	2, // 5: proto.ArenaService.GetArenaById:input_type -> proto.GetArenaRequest
	7, // 6: proto.ArenaService.GetArenas:input_type -> google.protobuf.Empty
	1, // 7: proto.ArenaService.CreateArena:output_type -> proto.ArenaResponse
	1, // 8: proto.ArenaService.DeleteArena:output_type -> proto.ArenaResponse
	1, // 9: proto.ArenaService.UpdateArena:output_type -> proto.ArenaResponse
	4, // 10: proto.ArenaService.GetArenaById:output_type -> proto.ArenaData
	5, // 11: proto.ArenaService.GetArenas:output_type -> proto.ListArenaResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_arena_proto_init() }
func file_proto_arena_proto_init() {
	if File_proto_arena_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_arena_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ArenaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_arena_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ArenaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_arena_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetArenaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_arena_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateArenaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_arena_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ArenaData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_arena_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ListArenaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_arena_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_arena_proto_goTypes,
		DependencyIndexes: file_proto_arena_proto_depIdxs,
		MessageInfos:      file_proto_arena_proto_msgTypes,
	}.Build()
	File_proto_arena_proto = out.File
	file_proto_arena_proto_rawDesc = nil
	file_proto_arena_proto_goTypes = nil
	file_proto_arena_proto_depIdxs = nil
}
